version: '3'
services:
  main.database:
    image: "microsoft/mssql-server-windows-developer"
    ports:
        - "3306:1433"
    volumes:
        - E:/Repos/data:C:/Repos/data
    environment:
        SA_PASSWORD: "S1mple@password"
        ACCEPT_EULA: "Y"
        COMPOSE_CONVERT_WINDOWS_PATHS: 1
        attach_dbs: '[ { "dbName": "FreeParkingSystem.Database", "dbFiles": [ "C:\\Repos\\data\\FreeParkingSystem.Database_Primary.mdf", "C:\\Repos\\data\\FreeParkingSystem.Database_Primary.ldf" ] } ]'
  rabbitmq:
    image: "rabbitmq:3"
    hostname: "free-parking-rabbitmq"    
    volumes:
        - E:/Repos/data/rabbitmq:/var/lib/rabbitmq
  accounts:
    depends_on:
        - main.database
        - rabbitmq
    image: free-parking-system-accounts
    build: 
        context: .
        dockerfile: .\src\Account\FreeParkingSystem.Accounts.API\dockerfile
    ports: 
        - "1000:80"
        - "1001:443"
    volumes: 
        - ${HOME}/.aspnet/https/:/https/
    environment: 
        Deployment_Environment_Name: "Staging" 
        Deployment_LogLevel_Default: "Information"
        Deployment_Db_Server: "main.database,1433"
        Deployment_Db_Name: "FreeParkingSystem.Database"
        Deployment_Db_User: "sa" 
        Deployment_Db_Password: "S1mple@password" 
        Deployment_PasswordOptions_MinimumCharacters: 4
        ASPNETCORE_ENVIRONMENT: "Staging"
        ASPNETCORE_URLS: "https://+;http://+"
        ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
        ASPNETCORE_Kestrel__Certificates__Default__Password: "P@55w0rd"
        ASPNETCORE_HTTPS_PORT: 1001
        ASPNETCORE_HTTP_PORT: 1000