version: '3'
services:
  db:
    image: "microsoft/mssql-server-windows-developer"
    container_name: db1
    ports:
        - "3306:1433"
    volumes:
        - E:/Repos/data:C:/Repos/data
    environment:
        SA_PASSWORD: "S1mple@password"
        ACCEPT_EULA: "Y"
        COMPOSE_CONVERT_WINDOWS_PATHS: 1
        attach_dbs: '[ { "dbName": "FreeParkingSystem.Database", "dbFiles": [ "C:\\Repos\\data\\FreeParkingSystem.Database_Primary.mdf", "C:\\Repos\\data\\FreeParkingSystem.Database_Primary.ldf" ] } ]'
