version: '3.4'

services:
  freeparkingsystem.webapp:
    image: freeparkingsystem.webapp
    build:
      context: .
      dockerfile: Core\FreeParkingSystem.WebApp\Dockerfile

  freeparkingsystem.accounts:
    image: freeparkingsystemaccounts
    build:
      context: .
      dockerfile: Core\FreeParkingSystem.Accounts\Dockerfile

