//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeParkingSystem.Orders.Contract.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Validations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeParkingSystem.Orders.Contract.Resources.Validations", typeof(Validations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested order is already cancelled..
        /// </summary>
        public static string Order_AlreadyCancelled {
            get {
                return ResourceManager.GetString("Order_AlreadyCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested order has already ended..
        /// </summary>
        public static string Order_AlreadyEnded {
            get {
                return ResourceManager.GetString("Order_AlreadyEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order can only be cancelled by the parking owner or the tenant..
        /// </summary>
        public static string Order_CanOnlyBeCancelledByTheOwnerOrTheTennant {
            get {
                return ResourceManager.GetString("Order_CanOnlyBeCancelledByTheOwnerOrTheTennant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested order does not exist..
        /// </summary>
        public static string Order_DoesNotExist {
            get {
                return ResourceManager.GetString("Order_DoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id is not valid..
        /// </summary>
        public static string Order_UserIdNotValid {
            get {
                return ResourceManager.GetString("Order_UserIdNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parking spot does not exist..
        /// </summary>
        public static string ParkingSpot_DoesNotExist {
            get {
                return ResourceManager.GetString("ParkingSpot_DoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parking spot is already leased.
        /// </summary>
        public static string ParkingSpot_IsAlreadyLeased {
            get {
                return ResourceManager.GetString("ParkingSpot_IsAlreadyLeased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Owner of the parking cannot lease the parking to himself.
        /// </summary>
        public static string ParkingSpot_OwnerCannotLeaseToHimself {
            get {
                return ResourceManager.GetString("ParkingSpot_OwnerCannotLeaseToHimself", resourceCulture);
            }
        }
    }
}
